### ISSUE TITLE
GPL3: Strange choice of license for wiki

### ISSUE THREAD

**Issue by sneumann** [RASpicer/MetabolomicsTools#5]
Hi, The GPL3 applies more to software, and less to a collection of text. 
I'd suggest to consider re-licensing to https://en.wikipedia.org/wiki/GNU_Free_Documentation_License
or one of the CreativeCommons versions (e.g. CC-BY). Yours, Steffen

**Comment by RASpicer** [comment]
The license has been update to GNU Free Documentation.
